// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package main

import (
	"errors"
	"fmt"
)

const (
	// ForYou is a MessageType of type ForYou.
	ForYou MessageType = "ForYou"
)

var ErrInvalidMessageType = errors.New("not a valid MessageType")

// String implements the Stringer interface.
func (x MessageType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x MessageType) IsValid() bool {
	_, err := ParseMessageType(string(x))
	return err == nil
}

var _MessageTypeValue = map[string]MessageType{
	"ForYou": ForYou,
}

// ParseMessageType attempts to convert a string to a MessageType.
func ParseMessageType(name string) (MessageType, error) {
	if x, ok := _MessageTypeValue[name]; ok {
		return x, nil
	}
	return MessageType(""), fmt.Errorf("%s is %w", name, ErrInvalidMessageType)
}

// MarshalText implements the text marshaller method.
func (x MessageType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *MessageType) UnmarshalText(text []byte) error {
	tmp, err := ParseMessageType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
