// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package message

import (
	"errors"
	"fmt"
)

const (
	// ProvideConnectionSign is a Type of type ProvideConnectionSign.
	ProvideConnectionSign Type = "ProvideConnectionSign"
	// ConnectionSignProvided is a Type of type ConnectionSignProvided.
	ConnectionSignProvided Type = "ConnectionSignProvide"
	// MakeOffer is a Type of type MakeOffer.
	MakeOffer Type = "MakeOffer"
	// SendOffer is a Type of type SendOffer.
	SendOffer Type = "SendOffer"
	// AnswerOffer is a Type of type AnswerOffer.
	AnswerOffer Type = "AnswerOffer"
	// SendAsnwer is a Type of type SendAsnwer.
	SendAsnwer Type = "SendAsnwer"
	// OfferAnswered is a Type of type OfferAnswered.
	OfferAnswered Type = "OfferAnswered"
	// ConnectionEstablished is a Type of type ConnectionEstablished.
	ConnectionEstablished Type = "ConnectionEstablished"
	// ErrReadMessage is a Type of type ErrReadMessage.
	ErrReadMessage Type = "ErrReadMessage"
	// Disconnected is a Type of type Disconnected.
	Disconnected Type = "Disconnected"
	// IamShotdown is a Type of type IamShotdown.
	IamShotdown Type = "IamShotdown"
	// HeadMemberID is a Type of type HeadMemberID.
	HeadMemberID Type = "HeadMemberID"
	// ForYou is a Type of type ForYou.
	ForYou Type = "ForYou"
	// NewConnection is a Type of type NewConnection.
	NewConnection Type = "NewConnection"
	// InteractionFailed is a Type of type InteractionFailed.
	InteractionFailed Type = "InteractionFailed"
)

var ErrInvalidType = errors.New("not a valid Type")

// String implements the Stringer interface.
func (x Type) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Type) IsValid() bool {
	_, err := ParseType(string(x))
	return err == nil
}

var _TypeValue = map[string]Type{
	"ProvideConnectionSign": ProvideConnectionSign,
	"ConnectionSignProvide": ConnectionSignProvided,
	"MakeOffer":             MakeOffer,
	"SendOffer":             SendOffer,
	"AnswerOffer":           AnswerOffer,
	"SendAsnwer":            SendAsnwer,
	"OfferAnswered":         OfferAnswered,
	"ConnectionEstablished": ConnectionEstablished,
	"ErrReadMessage":        ErrReadMessage,
	"Disconnected":          Disconnected,
	"IamShotdown":           IamShotdown,
	"HeadMemberID":          HeadMemberID,
	"ForYou":                ForYou,
	"NewConnection":         NewConnection,
	"InteractionFailed":     InteractionFailed,
}

// ParseType attempts to convert a string to a Type.
func ParseType(name string) (Type, error) {
	if x, ok := _TypeValue[name]; ok {
		return x, nil
	}
	return Type(""), fmt.Errorf("%s is %w", name, ErrInvalidType)
}

// MarshalText implements the text marshaller method.
func (x Type) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Type) UnmarshalText(text []byte) error {
	tmp, err := ParseType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
