// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package ctxtool

import (
	"errors"
	"fmt"
)

const (
	// KeySpan is a Key of type Span.
	KeySpan Key = iota
)

var ErrInvalidKey = errors.New("not a valid Key")

const _KeyName = "Span"

var _KeyMap = map[Key]string{
	KeySpan: _KeyName[0:4],
}

// String implements the Stringer interface.
func (x Key) String() string {
	if str, ok := _KeyMap[x]; ok {
		return str
	}
	return fmt.Sprintf("Key(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Key) IsValid() bool {
	_, ok := _KeyMap[x]
	return ok
}

var _KeyValue = map[string]Key{
	_KeyName[0:4]: KeySpan,
}

// ParseKey attempts to convert a string to a Key.
func ParseKey(name string) (Key, error) {
	if x, ok := _KeyValue[name]; ok {
		return x, nil
	}
	return Key(0), fmt.Errorf("%s is %w", name, ErrInvalidKey)
}
