// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package member

import (
	"errors"
	"fmt"
)

const (
	// NotVerified is a State of type Not_verified.
	NotVerified State = iota
	// Verified is a State of type Verified.
	Verified
)

var ErrInvalidState = errors.New("not a valid State")

const _StateName = "not_verifiedverifies"

var _StateMap = map[State]string{
	NotVerified: _StateName[0:12],
	Verified:    _StateName[12:20],
}

// String implements the Stringer interface.
func (x State) String() string {
	if str, ok := _StateMap[x]; ok {
		return str
	}
	return fmt.Sprintf("State(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x State) IsValid() bool {
	_, ok := _StateMap[x]
	return ok
}

var _StateValue = map[string]State{
	_StateName[0:12]:  NotVerified,
	_StateName[12:20]: Verified,
}

// ParseState attempts to convert a string to a State.
func ParseState(name string) (State, error) {
	if x, ok := _StateValue[name]; ok {
		return x, nil
	}
	return State(0), fmt.Errorf("%s is %w", name, ErrInvalidState)
}
